Fix Bugs/Issues of PowerFlow
NREL-Sienna/PowerFlows.jl pull request #45
Opened 2024-08-06 21:04 UTC by rodrigomha

Closes #44 #43 #40 #41

2024-08-06 21:06 UTC, rodrigomha commented
@GabrielKS @jd-lara The bug in the Q redistribution was that the units was hitting limits in iterative process of the remaining Q, but it was not correctly substracted to the residual in that case. This was fixed by replacing `reallocated_q += q_frac` by  `reallocated_q += q_set_point - current_q` and properly checking the condition of the limits by using `q_frac + current_q` rather than the clamped value.

2024-08-06 21:13 UTC, rodrigomha commented
Regarding the tests: Tests are failing for the net_flows with the update of #41.

@GabrielKS @jd-lara Let me know if we are OK with adding the symmetrical and I will update the tests to change the zeros for negative values if needed, or going back to only having one direction and the other zero.

2024-08-06 21:21 UTC, GabrielKS commented
> Regarding the tests: Tests are failing for the net_flows with the update of #41.
> 
> @GabrielKS @jd-lara Let me know if we are OK with adding the symmetrical and I will update the tests to change the zeros for negative values if needed, or going back to only having one direction and the other zero.

I like the behavior you have implemented.

2024-08-06 21:29 UTC, GabrielKS requested changes
Looks good aside from the test failures.

2024-08-07 19:12 UTC, GabrielKS requested changes

2024-08-07 19:12 UTC, GabrielKS commented on test/test_dc_powerflow.jl
> +        solved_data_ABA["1"]["flow_results"].P_from_to,
Shouldn't we also test that the value of `P_to_from` is the opposite of `P_from_to`?

2024-08-07 19:12 UTC, GabrielKS commented on src/post_processing.jl
> +            if it > 5
Maybe define this as a constant somewhere to reduce magic numbers?

2024-08-12 16:46 UTC, rodrigomha commented
@GabrielKS It is ready for review.

There is now one kwarg when calling `solve_ac_powerflow!`: `max_redistribution_iterations` that controls the max number of redistribution iterations

2024-08-12 17:49 UTC, GabrielKS approved these changes
LGTM

2024-08-12 17:49 UTC, merged